### ISSUE TITLE
Feature req: Select multiple text items

### ISSUE THREAD

**Issue by Miloua91** [Miloua91/clipwarp#13]
Add the abilty to select multiple items then copy the text inside or delete them.

### TODO
- [ ] Select per item.
- [ ] Select all items.
- [ ] Copy or delete the items.

### Platform
- [ ] Desktop
- [ ] Web
- [ ] Mobile

<br>

<img src="https://github.com/user-attachments/assets/b98e155e-4aea-46ad-a69d-ad95f3cce627" height='800px'>
